version: "3.8"
services:
  backend:
    container_name: docker_supervisord
    env_file:
      - env.env
    environment:
      - COMPOSE_ENV=/usr/local/
    build:
      context: .
      dockerfile: ./apps/Dockerfile
    working_dir: /opt/server
    command:
      - "echo"
      - "$$(whoami)"
    ports:
      - 9002:9002
      - 9003:9003
    networks:
      - docker_supervisord

networks:
  docker_supervisord:
    driver: bridge