version: "3.8"
services:
  backend:
    container_name: docker_supervisord
    env_file:
      - env.env
    build:
      context: .
      dockerfile: ./apps/Dockerfile
    command: supervisord -n -c supervisord.conf
    ports:
      - 9002:9002
      - 9003:9003
    networks:
      - docker_supervisord
networks:
  docker_supervisord:
    driver: bridge